In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4829, 9424, 4914, 3748],
 [4829, 9424, 4914, 7787],
 [4829, 3935, 4914, 2876],
 [4411, 3083, 4725, 1400, 9334],
 [4411, 3083, 4725, 1400, 8689],
 [3682, 4829, 979, 4914, 3034],
 [169, 2640, 1238, 1400]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [25]:
sent_length=10
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0    0    0 4829 9424 4914 3748]
 [   0    0    0    0    0    0 4829 9424 4914 7787]
 [   0    0    0    0    0    0 4829 3935 4914 2876]
 [   0    0    0    0    0 4411 3083 4725 1400 9334]
 [   0    0    0    0    0 4411 3083 4725 1400 8689]
 [   0    0    0    0    0 3682 4829  979 4914 3034]
 [   0    0    0    0    0    0  169 2640 1238 1400]]


In [26]:
## feature representation
dim=8

In [27]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [28]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step


array([[[ 7.8144073e-03, -4.9916804e-02, -1.3681762e-03, -8.3698407e-03,
         -2.7383078e-02,  2.4363030e-02,  1.0426391e-02, -3.1191373e-02],
        [ 7.8144073e-03, -4.9916804e-02, -1.3681762e-03, -8.3698407e-03,
         -2.7383078e-02,  2.4363030e-02,  1.0426391e-02, -3.1191373e-02],
        [ 7.8144073e-03, -4.9916804e-02, -1.3681762e-03, -8.3698407e-03,
         -2.7383078e-02,  2.4363030e-02,  1.0426391e-02, -3.1191373e-02],
        [ 7.8144073e-03, -4.9916804e-02, -1.3681762e-03, -8.3698407e-03,
         -2.7383078e-02,  2.4363030e-02,  1.0426391e-02, -3.1191373e-02],
        [ 7.8144073e-03, -4.9916804e-02, -1.3681762e-03, -8.3698407e-03,
         -2.7383078e-02,  2.4363030e-02,  1.0426391e-02, -3.1191373e-02],
        [ 7.8144073e-03, -4.9916804e-02, -1.3681762e-03, -8.3698407e-03,
         -2.7383078e-02,  2.4363030e-02,  1.0426391e-02, -3.1191373e-02],
        [ 8.2338564e-03, -2.8898740e-02, -1.6064726e-02,  1.5110854e-02,
         -8.8342428e-03, -2.5184810e-02,  2.1

In [30]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0, 4829, 9424, 4914, 3748])

In [ ]:
model.predict(embedded_docs[0])