In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4829, 9424, 4914, 3748],
 [4829, 9424, 4914, 7787],
 [4829, 3935, 4914, 2876],
 [4411, 3083, 4725, 1400, 9334],
 [4411, 3083, 4725, 1400, 8689],
 [3682, 4829, 979, 4914, 3034],
 [169, 2640, 1238, 1400]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4829 9424 4914 3748]
 [   0    0    0    0 4829 9424 4914 7787]
 [   0    0    0    0 4829 3935 4914 2876]
 [   0    0    0 4411 3083 4725 1400 9334]
 [   0    0    0 4411 3083 4725 1400 8689]
 [   0    0    0 3682 4829  979 4914 3034]
 [   0    0    0    0  169 2640 1238 1400]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\sachi\.conda\envs\compvision\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step


array([[[-3.71482000e-02, -7.32206181e-03,  1.28859542e-02,
          6.26540184e-03,  1.82773732e-02,  2.60131992e-02,
         -3.44377756e-03,  1.54060237e-02,  2.99514271e-02,
         -7.74573162e-03],
        [-3.71482000e-02, -7.32206181e-03,  1.28859542e-02,
          6.26540184e-03,  1.82773732e-02,  2.60131992e-02,
         -3.44377756e-03,  1.54060237e-02,  2.99514271e-02,
         -7.74573162e-03],
        [-3.71482000e-02, -7.32206181e-03,  1.28859542e-02,
          6.26540184e-03,  1.82773732e-02,  2.60131992e-02,
         -3.44377756e-03,  1.54060237e-02,  2.99514271e-02,
         -7.74573162e-03],
        [-3.71482000e-02, -7.32206181e-03,  1.28859542e-02,
          6.26540184e-03,  1.82773732e-02,  2.60131992e-02,
         -3.44377756e-03,  1.54060237e-02,  2.99514271e-02,
         -7.74573162e-03],
        [ 2.04255469e-02, -5.25510311e-03,  2.94775106e-02,
          3.10885943e-02,  3.99741419e-02,  1.00074038e-02,
          1.17691159e-02,  4.92535345e-02,  8.368872